export default {
  apiKey: 'YRAmfjRhq2AI5EYQpSKAdCQgJvXzkDdEKF5orvnJAFBtMNzdTziWuGO7J0ctGJta',
  kw: '技术',
  pageSize: 10,
  menuData: [{
    name: '人脸识别',
    url: '/pages/faceScans/index',
    openType: 'navigate',
  }, {
    name: '相机扫描',
    url: '/pages/cameraScans/index',
    openType: 'navigate',
  }, {
    name: '云课堂',
    url: '/pages/courses/courses',
    openType: 'navigate',
  }, {
    name: '新闻',
    url: '/pages/new/new',
    openType: 'navigate',
  }, {
    name: '音乐',
    url: '/pages/music/music',
    openType: 'navigate',
  }, {
    name: '视频',
    url: '/pages/video/video',
    openType: 'navigate',
  }, {
    name: '图片',
    url: '/pages/picture/picture',
    openType: 'navigate',
  }, {
    name: '读书',
    url: '/pages/yuedu/yuedu',
    openType: 'switchTab',
  }, {
    name: 'BBC',
    url: '/pages/bbc/bbc',
    openType: 'navigate',
  }, {
    name: '记事本',
    url: '',
    openType: 'navigate',
  }, {
    name: 'TodoList',
    url: '',
    openType: 'navigate',
  }, {
    name: '游戏',
    url: '',
    openType: 'navigate',
  }, {
    name: '动画',
    url: '/pages/animation/animation',
    openType: 'navigate',
  }, {
    name: 'scroll',
    url: '/pages/scroll/scroll',
    openType: 'navigate',
  }, {
    name: '首页',
    url: '/pages/index/index',
    openType: 'switchTab',
  }, {
    name: 'Logs',
    url: '/pages/logs/logs',
    openType: 'switchTab'
  }, {
    name: 'WeUI',
    url: '/index/index',
    openType: 'redirect'
  }, {
    name: 'WXApi',
    url: '/index/api/api',
    openType: 'navigate',
  }]
};